version: '3'
services: 
    client:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: .
        volumes: 
            - /app/node_modules
            - ./:/app